<?php

return array(
    "inventory" => __("Inventory", 'us-barcode-scanner'),
    "orders" => __("Orders", 'us-barcode-scanner'),
    "create_order" => __("Create Order", 'us-barcode-scanner'),
    "close" => __("Close", 'us-barcode-scanner'),
    "dont_have_actions_permissions" => __("You don't have permissions to this actions", 'us-barcode-scanner'),
    "open_product" => __("Open product in new tab", 'us-barcode-scanner'),
    "open_order" => __("Open order in new tab", 'us-barcode-scanner'),
    "find_item_and_open" => __("Find item and open it in new a window for editing.", 'us-barcode-scanner'),
    "open_created_order" => __("Open created order in new a window for editing.", 'us-barcode-scanner'),
    "stock_minus" => __("Decrease QTY (-1)", 'us-barcode-scanner'),
    "stock_minus_info" => __("Decrease product quantity right after you scan product barcode.", 'us-barcode-scanner'),
    "stock_plus" => __("Increase QTY (+1)", 'us-barcode-scanner'),
    "stock_plus_info" => __("Increase product quantity right after you scan product barcode.", 'us-barcode-scanner'),
    "do_after_search" => __("Search mode:", 'us-barcode-scanner'),
    "toggle_mute" => __("Toggle mute", 'us-barcode-scanner'),
    "looking_for_item" => __("Looking for item...", 'us-barcode-scanner'),
    "variation" => __("variation", 'us-barcode-scanner'),
    "search_too_long" => __("Search takes too long.", 'us-barcode-scanner'),
    "optimize_search" => __("OPTIMIZE SEARCH", 'us-barcode-scanner'),
    "scan_barcode" => __("Scan barcode", 'us-barcode-scanner'),
    "type_fields" => __("Type ID/SKU/Name", 'us-barcode-scanner'),
    "not_found" => __("Not found", 'us-barcode-scanner'),
    "create" => __("Create", 'us-barcode-scanner'),
    "refresh" => __("refresh", 'us-barcode-scanner'),
    "stock_disabled" => __("Stock is disabled", 'us-barcode-scanner'),
    "qty_not_available" => __("Qty not available for external items", 'us-barcode-scanner'),
    "enable" => __("enable", 'us-barcode-scanner'),
    "variation_use_parent_1" => __("This variation configured to use parent quantity. If you need separate quantity for this variation then enable ", 'us-barcode-scanner'),
    "manage_stock" => __("Manage stock", 'us-barcode-scanner'),
    "variation_use_parent_2" => __("option for variation on", 'us-barcode-scanner'),
    "product_page" => __("product page", 'us-barcode-scanner'),
    "more" => __("more", 'us-barcode-scanner'),
    "parent_quantity" => __("Parent quantity", 'us-barcode-scanner'),
    "regular_price" => __("Regular price", 'us-barcode-scanner'),
    "price_is_not_editable" => __("Price is not editable for parent product.", 'us-barcode-scanner'),
    "change_status" => __("Change Status", 'us-barcode-scanner'),
    "find_order_and_change_status" => __("Find order and change status", 'us-barcode-scanner'),

    "we_are_sorry" => __("We are sorry", 'us-barcode-scanner'),
    "increase_search_speed" => __("Increase search speed", 'us-barcode-scanner'),
    "cancel" => __("CANCEL", 'us-barcode-scanner'),
    "start" => __("START", 'us-barcode-scanner'),

    "err_close" => __("Close", 'us-barcode-scanner'),
    "err_check_again" => __("Check again", 'us-barcode-scanner'),
    "cart_reload" => __("Update cart", 'us-barcode-scanner'),

    "order" => __("Order", 'us-barcode-scanner'),
    "created" => __("created", 'us-barcode-scanner'),
    "cancel_order" => __("Clear", 'us-barcode-scanner'),
    "cancel_attributes" => __("Cancel", 'us-barcode-scanner'),
    "order_status" => __("Status", 'us-barcode-scanner'),
    "shipping_methods" => __("Shipping", 'us-barcode-scanner'),
    "payment_methods" => __("Payment", 'us-barcode-scanner'),
    "customer_note" => __("Customer provided note", 'us-barcode-scanner'),
    "apply_attributes" => __("Apply", 'us-barcode-scanner'),
    "fill_attributes" => __("Fill attributes to add product:", 'us-barcode-scanner'),
    "fill_qty" => __("This product is out of stock", 'us-barcode-scanner'),
    "fill_qty_2" => __("Not enough stock quantity", 'us-barcode-scanner'),
    "fill_would_u_inc_qty" => __("Increase quantity to:", 'us-barcode-scanner'),
    "fill_cant_add_item" => __("Can't add item:", 'us-barcode-scanner'),
    "username" => __("Username", 'us-barcode-scanner'),
    "enter_username_link" => __("Customer", 'us-barcode-scanner'),
    "enter_username" => __("Enter username", 'us-barcode-scanner'),
    "email" => __("Email", 'us-barcode-scanner'),
    "enter_email" => __("Enter user email", 'us-barcode-scanner'),
    "create_user" => __("Create user", 'us-barcode-scanner'),
    "user" => __("User", 'us-barcode-scanner'),
    "incl_tax" => __("(incl. tax)", 'us-barcode-scanner'),

    "product" => __("Product", 'us-barcode-scanner'),
    "price" => __("Price", 'us-barcode-scanner'),
    "qty" => __("Qty", 'us-barcode-scanner'),
    "total" => __("Total", 'us-barcode-scanner'),
    "subtotal" => __("Subtotal", 'us-barcode-scanner'),
    "find_add_products" => __("Find & add products", 'us-barcode-scanner'),
    "discount" => __("Discount", 'us-barcode-scanner'),

    "search_fields_languages" => __("search fields & languages", 'us-barcode-scanner'),
    "search_fields" => __("search fields", 'us-barcode-scanner'),
    "success" => __("Success", 'us-barcode-scanner'),

    "time_left" => __("Time left:", 'us-barcode-scanner'),
    "takes_too_long" => __("Takes too long?", 'us-barcode-scanner'),
    "optimize" => __("Optimize", 'us-barcode-scanner'),

    "search_type_scan" => __("Scan", 'us-barcode-scanner'),
    "search_type_enter" => __("Enter", 'us-barcode-scanner'),
    "search" => __("Search", 'us-barcode-scanner'),

    "filter_search_fields" => __("Search fields", 'us-barcode-scanner'),
    "filter_search_fields_info" => __("Select fields that will be used to find products and orders", 'us-barcode-scanner'),
    "filter_products" => __("Products", 'us-barcode-scanner'),
    "filter_variation_description" => __("Variation Description", 'us-barcode-scanner'),
    "filter_custom_field_name" => __("Custom field name", 'us-barcode-scanner'),
    "filter_orders" => __("Orders", 'us-barcode-scanner'),
    "filter_languages" => __("languages", 'us-barcode-scanner'),
    "filter_cancel" => __("Cancel", 'us-barcode-scanner'),
    "filter_save" => __("Save", 'us-barcode-scanner'),

    "order_tax" => __("Tax:", 'us-barcode-scanner'),
    "order_total" => __("Order Total:", 'us-barcode-scanner'),
    "order_items_subtotal" => __("Items Subtotal:", 'us-barcode-scanner'),
    "order_create_user" => __("Create new customer", 'us-barcode-scanner'),
    "order_scan_barcode" => __("Scan barcode", 'us-barcode-scanner'),
    "order_type" => __("Type ID", 'us-barcode-scanner'),
    "order_customer_note" => __("Customer note:", 'us-barcode-scanner'),
    "billing" => __("Billing", 'us-barcode-scanner'),
    "shipping" => __("Shipping", 'us-barcode-scanner'),

    "check_internet_connection" => __("Check internet connection.", 'us-barcode-scanner'),
    "try_to_optimize_search" => __("Try to optimize search.", 'us-barcode-scanner'),

    "indexation_prepare" => __("Indexation", 'us-barcode-scanner'),
    "indexation_prepare_info" => __("Run full indexation of the products & orders to speed up the search.<br/>Do not close the main popup till indexation is completed.", 'us-barcode-scanner'),
    "full_indexation" => __("Full Indexation", 'us-barcode-scanner'),
    "fast_indexation" => __("Fast Indexation", 'us-barcode-scanner'),
    "bg_indexing_in_progress" => __("Indexing in progress", 'us-barcode-scanner'),
    "bg_products_not_indexed_yet" => __("products not indexed yet.", 'us-barcode-scanner'),
    "bg_indexing_info" => __("Meanwhile you can use search but unindexed products won’t be found.", 'us-barcode-scanner'),
    "bg_indexed_successfully" => __("products indexed successfully", 'us-barcode-scanner'),

    "show_locations" => __("Show locations", 'us-barcode-scanner'),
    "hide" => __("Hide", 'us-barcode-scanner'),

    "print_label" => __("Print Label", 'us-barcode-scanner'),
    "product_link" => __("Product Link", 'us-barcode-scanner'),

    "published" => __("Published", 'us-barcode-scanner'),
    "publish" => __("Publish", 'us-barcode-scanner'),
    "pending" => __("Pending", 'us-barcode-scanner'),
    "draft" => __("Draft", 'us-barcode-scanner'),
    "pending review" => __("Pending Review", 'us-barcode-scanner'),
    "privately published" => __("Privately Published", 'us-barcode-scanner'),
    "draft" => __("Draft", 'us-barcode-scanner'),
    "post_excerpt" => __("Post excerpt", 'us-barcode-scanner'),
);
